name: NodeJS

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:

  complete:
    if: always()
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
      run: exit 1

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stellar/actions/rust-cache@main
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - run: make build
    - run: cargo install_soroban
    - uses: actions/setup-node@v3
      with:
        node-version: 18.14.2
        cache: 'npm'
    - run: |
        mkdir -p .soroban
        echo 'futurenet' > .soroban/network
        echo 'CCY3P2KYW3A6SEMH7QHDA6U7LQUMRJP57IFDAQPLJL3KO2GF2YTH444B' > .soroban/abundance_token_id
        echo 'CDRCSILOO5XENYXCE7FYCLJZ5U2QU4AARLJSIMEISS4WVHLXVWKQ6EC2' > .soroban/crowdfund_id
        echo 'Test SDF Network ; September 2015' > .soroban/passphrase
        echo 'https://soroban-testnet.stellar.org/' > .soroban/rpc-url
        echo '{"network":"testnet","rpcUrl":"https://soroban-testnet.stellar.org","networkPassphrase":"Test SDF Network ; September 2015"}' > shared/config.json
    - run: npm ci
    - run: npm run build